image:
  repository: "sergeis8v/wordpress-prod"
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

service:
  type: ClusterIP
  port: 80

persistentVolumeClaim:
  storageSize: 10Gi

extraEnvs:
  - name: WORDPRESS_DB_HOST
    value: wordpress-mysql:3306
  - name: WORDPRESS_DB_NAME
    value: wordpressdb
  - name: WORDPRESS_DB_USER
    value: root
  - name: WORDPRESS_DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: mysql-pass
        key: password
  - name: WP_DEBUG_LOG
    value: "true"