name: Production Build, Push Docker images and Helm package

on:
  push:
    branches:
    - "main"
    # paths-ignore:
    #   - '.github/**'

jobs:
  release-image:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: ""
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push the Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./src
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/wordpress-prod:${{ steps.tag_version.outputs.new_tag }}

    - name: Helm tool installer
      uses: Azure/setup-helm@v1

    - name: Package Helm chart
      run: |
        helm package chart/wordpress --version=${{ steps.tag_version.outputs.new_tag }} --app-version=${{ steps.tag_version.outputs.new_tag }}

    - name: Publish Helm Chart
      run: |
        curl -H "X-JFrog-Art-Api:${{ secrets.X_JFROG_ART_API }}" -T $(find . -name 'wordpress*.tgz') "https://sergeisv.jfrog.io/artifactory/sergeisv-helm/$(find . -name 'wordpress*.tgz')"
